export TEST_MAX_ROWCNT=1000000
export TEST_TARGET_EPS=0
export TEST_PORT_NO=5656
export TEST_SERVER_IP=127.0.0.1
echo "TEST_MAX_ROWCNT_TIME : $TEST_MAX_ROWCNT"
echo "TEST_TARGET_EPS : $TEST_TARGET_EPS"
echo "TEST_PORT_NO : $TEST_PORT_NO"
echo "TEST_SERVER_IP : $TEST_SERVER_IP"

